// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Address struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Envelope struct {
	From                 *Address   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   []*Address `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Message              *any.Any   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Envelope) Reset()         { *m = Envelope{} }
func (m *Envelope) String() string { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()    {}
func (*Envelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *Envelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Envelope.Unmarshal(m, b)
}
func (m *Envelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Envelope.Marshal(b, m, deterministic)
}
func (m *Envelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Envelope.Merge(m, src)
}
func (m *Envelope) XXX_Size() int {
	return xxx_messageInfo_Envelope.Size(m)
}
func (m *Envelope) XXX_DiscardUnknown() {
	xxx_messageInfo_Envelope.DiscardUnknown(m)
}

var xxx_messageInfo_Envelope proto.InternalMessageInfo

func (m *Envelope) GetFrom() *Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Envelope) GetTo() []*Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Envelope) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

type Block struct {
	Index                uint64   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Data                 *any.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Block) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type Proof struct {
	Block                *Block   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proof) Reset()         { *m = Proof{} }
func (m *Proof) String() string { return proto.CompactTextString(m) }
func (*Proof) ProtoMessage()    {}
func (*Proof) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *Proof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proof.Unmarshal(m, b)
}
func (m *Proof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proof.Marshal(b, m, deterministic)
}
func (m *Proof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proof.Merge(m, src)
}
func (m *Proof) XXX_Size() int {
	return xxx_messageInfo_Proof.Size(m)
}
func (m *Proof) XXX_DiscardUnknown() {
	xxx_messageInfo_Proof.DiscardUnknown(m)
}

var xxx_messageInfo_Proof proto.InternalMessageInfo

func (m *Proof) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type Event struct {
	Block                *Block   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type Transaction struct {
	ContractID           string   `protobuf:"bytes,1,opt,name=contractID,proto3" json:"contractID,omitempty"`
	Action               string   `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Body                 *any.Any `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{5}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetContractID() string {
	if m != nil {
		return m.ContractID
	}
	return ""
}

func (m *Transaction) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Transaction) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

type TransactionResult struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Accepted             bool         `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Instances            [][]byte     `protobuf:"bytes,3,rep,name=instances,proto3" json:"instances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TransactionResult) Reset()         { *m = TransactionResult{} }
func (m *TransactionResult) String() string { return proto.CompactTextString(m) }
func (*TransactionResult) ProtoMessage()    {}
func (*TransactionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{6}
}

func (m *TransactionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionResult.Unmarshal(m, b)
}
func (m *TransactionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionResult.Marshal(b, m, deterministic)
}
func (m *TransactionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResult.Merge(m, src)
}
func (m *TransactionResult) XXX_Size() int {
	return xxx_messageInfo_TransactionResult.Size(m)
}
func (m *TransactionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResult.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResult proto.InternalMessageInfo

func (m *TransactionResult) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *TransactionResult) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

func (m *TransactionResult) GetInstances() [][]byte {
	if m != nil {
		return m.Instances
	}
	return nil
}

type Instance struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *any.Any `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	AccessControl        []byte   `protobuf:"bytes,3,opt,name=accessControl,proto3" json:"accessControl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{7}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Instance) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Instance) GetAccessControl() []byte {
	if m != nil {
		return m.AccessControl
	}
	return nil
}

type CalypsoWrite struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	U                    []byte   `protobuf:"bytes,2,opt,name=u,proto3" json:"u,omitempty"`
	Ubar                 []byte   `protobuf:"bytes,3,opt,name=ubar,proto3" json:"ubar,omitempty"`
	E                    []byte   `protobuf:"bytes,4,opt,name=e,proto3" json:"e,omitempty"`
	F                    []byte   `protobuf:"bytes,5,opt,name=f,proto3" json:"f,omitempty"`
	C                    []byte   `protobuf:"bytes,6,opt,name=c,proto3" json:"c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalypsoWrite) Reset()         { *m = CalypsoWrite{} }
func (m *CalypsoWrite) String() string { return proto.CompactTextString(m) }
func (*CalypsoWrite) ProtoMessage()    {}
func (*CalypsoWrite) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{8}
}

func (m *CalypsoWrite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalypsoWrite.Unmarshal(m, b)
}
func (m *CalypsoWrite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalypsoWrite.Marshal(b, m, deterministic)
}
func (m *CalypsoWrite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalypsoWrite.Merge(m, src)
}
func (m *CalypsoWrite) XXX_Size() int {
	return xxx_messageInfo_CalypsoWrite.Size(m)
}
func (m *CalypsoWrite) XXX_DiscardUnknown() {
	xxx_messageInfo_CalypsoWrite.DiscardUnknown(m)
}

var xxx_messageInfo_CalypsoWrite proto.InternalMessageInfo

func (m *CalypsoWrite) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CalypsoWrite) GetU() []byte {
	if m != nil {
		return m.U
	}
	return nil
}

func (m *CalypsoWrite) GetUbar() []byte {
	if m != nil {
		return m.Ubar
	}
	return nil
}

func (m *CalypsoWrite) GetE() []byte {
	if m != nil {
		return m.E
	}
	return nil
}

func (m *CalypsoWrite) GetF() []byte {
	if m != nil {
		return m.F
	}
	return nil
}

func (m *CalypsoWrite) GetC() []byte {
	if m != nil {
		return m.C
	}
	return nil
}

type CalypsoRead struct {
	WriteID              []byte   `protobuf:"bytes,1,opt,name=writeID,proto3" json:"writeID,omitempty"`
	Xc                   []byte   `protobuf:"bytes,2,opt,name=xc,proto3" json:"xc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalypsoRead) Reset()         { *m = CalypsoRead{} }
func (m *CalypsoRead) String() string { return proto.CompactTextString(m) }
func (*CalypsoRead) ProtoMessage()    {}
func (*CalypsoRead) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{9}
}

func (m *CalypsoRead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalypsoRead.Unmarshal(m, b)
}
func (m *CalypsoRead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalypsoRead.Marshal(b, m, deterministic)
}
func (m *CalypsoRead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalypsoRead.Merge(m, src)
}
func (m *CalypsoRead) XXX_Size() int {
	return xxx_messageInfo_CalypsoRead.Size(m)
}
func (m *CalypsoRead) XXX_DiscardUnknown() {
	xxx_messageInfo_CalypsoRead.DiscardUnknown(m)
}

var xxx_messageInfo_CalypsoRead proto.InternalMessageInfo

func (m *CalypsoRead) GetWriteID() []byte {
	if m != nil {
		return m.WriteID
	}
	return nil
}

func (m *CalypsoRead) GetXc() []byte {
	if m != nil {
		return m.Xc
	}
	return nil
}

type DKGInit struct {
	Addresses            []*Address `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DKGInit) Reset()         { *m = DKGInit{} }
func (m *DKGInit) String() string { return proto.CompactTextString(m) }
func (*DKGInit) ProtoMessage()    {}
func (*DKGInit) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{10}
}

func (m *DKGInit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DKGInit.Unmarshal(m, b)
}
func (m *DKGInit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DKGInit.Marshal(b, m, deterministic)
}
func (m *DKGInit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DKGInit.Merge(m, src)
}
func (m *DKGInit) XXX_Size() int {
	return xxx_messageInfo_DKGInit.Size(m)
}
func (m *DKGInit) XXX_DiscardUnknown() {
	xxx_messageInfo_DKGInit.DiscardUnknown(m)
}

var xxx_messageInfo_DKGInit proto.InternalMessageInfo

func (m *DKGInit) GetAddresses() []*Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type EncryptedDeal struct {
	DHKey                []byte   `protobuf:"bytes,1,opt,name=DHKey,proto3" json:"DHKey,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Nonce                []byte   `protobuf:"bytes,3,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Cipher               []byte   `protobuf:"bytes,4,opt,name=Cipher,proto3" json:"Cipher,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedDeal) Reset()         { *m = EncryptedDeal{} }
func (m *EncryptedDeal) String() string { return proto.CompactTextString(m) }
func (*EncryptedDeal) ProtoMessage()    {}
func (*EncryptedDeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{11}
}

func (m *EncryptedDeal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedDeal.Unmarshal(m, b)
}
func (m *EncryptedDeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedDeal.Marshal(b, m, deterministic)
}
func (m *EncryptedDeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedDeal.Merge(m, src)
}
func (m *EncryptedDeal) XXX_Size() int {
	return xxx_messageInfo_EncryptedDeal.Size(m)
}
func (m *EncryptedDeal) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedDeal.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedDeal proto.InternalMessageInfo

func (m *EncryptedDeal) GetDHKey() []byte {
	if m != nil {
		return m.DHKey
	}
	return nil
}

func (m *EncryptedDeal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *EncryptedDeal) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *EncryptedDeal) GetCipher() []byte {
	if m != nil {
		return m.Cipher
	}
	return nil
}

type DKGDeal struct {
	Index                uint32         `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Deal                 *EncryptedDeal `protobuf:"bytes,2,opt,name=deal,proto3" json:"deal,omitempty"`
	Signature            []byte         `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DKGDeal) Reset()         { *m = DKGDeal{} }
func (m *DKGDeal) String() string { return proto.CompactTextString(m) }
func (*DKGDeal) ProtoMessage()    {}
func (*DKGDeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{12}
}

func (m *DKGDeal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DKGDeal.Unmarshal(m, b)
}
func (m *DKGDeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DKGDeal.Marshal(b, m, deterministic)
}
func (m *DKGDeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DKGDeal.Merge(m, src)
}
func (m *DKGDeal) XXX_Size() int {
	return xxx_messageInfo_DKGDeal.Size(m)
}
func (m *DKGDeal) XXX_DiscardUnknown() {
	xxx_messageInfo_DKGDeal.DiscardUnknown(m)
}

var xxx_messageInfo_DKGDeal proto.InternalMessageInfo

func (m *DKGDeal) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DKGDeal) GetDeal() *EncryptedDeal {
	if m != nil {
		return m.Deal
	}
	return nil
}

func (m *DKGDeal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type DKGResponse struct {
	Index                uint32                `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Response             *DKGResponse_Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DKGResponse) Reset()         { *m = DKGResponse{} }
func (m *DKGResponse) String() string { return proto.CompactTextString(m) }
func (*DKGResponse) ProtoMessage()    {}
func (*DKGResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{13}
}

func (m *DKGResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DKGResponse.Unmarshal(m, b)
}
func (m *DKGResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DKGResponse.Marshal(b, m, deterministic)
}
func (m *DKGResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DKGResponse.Merge(m, src)
}
func (m *DKGResponse) XXX_Size() int {
	return xxx_messageInfo_DKGResponse.Size(m)
}
func (m *DKGResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DKGResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DKGResponse proto.InternalMessageInfo

func (m *DKGResponse) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DKGResponse) GetResponse() *DKGResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type DKGResponse_Response struct {
	SessionID            []byte   `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Status               bool     `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DKGResponse_Response) Reset()         { *m = DKGResponse_Response{} }
func (m *DKGResponse_Response) String() string { return proto.CompactTextString(m) }
func (*DKGResponse_Response) ProtoMessage()    {}
func (*DKGResponse_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{13, 0}
}

func (m *DKGResponse_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DKGResponse_Response.Unmarshal(m, b)
}
func (m *DKGResponse_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DKGResponse_Response.Marshal(b, m, deterministic)
}
func (m *DKGResponse_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DKGResponse_Response.Merge(m, src)
}
func (m *DKGResponse_Response) XXX_Size() int {
	return xxx_messageInfo_DKGResponse_Response.Size(m)
}
func (m *DKGResponse_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_DKGResponse_Response.DiscardUnknown(m)
}

var xxx_messageInfo_DKGResponse_Response proto.InternalMessageInfo

func (m *DKGResponse_Response) GetSessionID() []byte {
	if m != nil {
		return m.SessionID
	}
	return nil
}

func (m *DKGResponse_Response) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DKGResponse_Response) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *DKGResponse_Response) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type DKGDone struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DKGDone) Reset()         { *m = DKGDone{} }
func (m *DKGDone) String() string { return proto.CompactTextString(m) }
func (*DKGDone) ProtoMessage()    {}
func (*DKGDone) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{14}
}

func (m *DKGDone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DKGDone.Unmarshal(m, b)
}
func (m *DKGDone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DKGDone.Marshal(b, m, deterministic)
}
func (m *DKGDone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DKGDone.Merge(m, src)
}
func (m *DKGDone) XXX_Size() int {
	return xxx_messageInfo_DKGDone.Size(m)
}
func (m *DKGDone) XXX_DiscardUnknown() {
	xxx_messageInfo_DKGDone.DiscardUnknown(m)
}

var xxx_messageInfo_DKGDone proto.InternalMessageInfo

func (m *DKGDone) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func init() {
	proto.RegisterType((*Address)(nil), "types.Address")
	proto.RegisterType((*Envelope)(nil), "types.Envelope")
	proto.RegisterType((*Block)(nil), "types.Block")
	proto.RegisterType((*Proof)(nil), "types.Proof")
	proto.RegisterType((*Event)(nil), "types.Event")
	proto.RegisterType((*Transaction)(nil), "types.Transaction")
	proto.RegisterType((*TransactionResult)(nil), "types.TransactionResult")
	proto.RegisterType((*Instance)(nil), "types.Instance")
	proto.RegisterType((*CalypsoWrite)(nil), "types.CalypsoWrite")
	proto.RegisterType((*CalypsoRead)(nil), "types.CalypsoRead")
	proto.RegisterType((*DKGInit)(nil), "types.DKGInit")
	proto.RegisterType((*EncryptedDeal)(nil), "types.EncryptedDeal")
	proto.RegisterType((*DKGDeal)(nil), "types.DKGDeal")
	proto.RegisterType((*DKGResponse)(nil), "types.DKGResponse")
	proto.RegisterType((*DKGResponse_Response)(nil), "types.DKGResponse.Response")
	proto.RegisterType((*DKGDone)(nil), "types.DKGDone")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 654 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5f, 0x6b, 0xd4, 0x4e,
	0x14, 0x25, 0xd9, 0xcd, 0x6e, 0xf6, 0x6e, 0x5a, 0x7e, 0xbf, 0xa1, 0x94, 0xb4, 0x4a, 0x29, 0x41,
	0xb0, 0xa8, 0xa4, 0xa0, 0x42, 0x9f, 0x6b, 0xb7, 0xd4, 0x52, 0x10, 0x19, 0x05, 0x9f, 0x67, 0x93,
	0xbb, 0x6b, 0x68, 0x3a, 0x13, 0x33, 0x93, 0xda, 0xbc, 0xf8, 0xe2, 0x37, 0xf4, 0x13, 0xc9, 0xfc,
	0xd9, 0x24, 0x95, 0x5a, 0x7c, 0x9b, 0x73, 0xe7, 0xcc, 0x3d, 0xe7, 0xde, 0x3b, 0x17, 0xb6, 0x6f,
	0x50, 0x4a, 0xb6, 0x46, 0x99, 0x56, 0xb5, 0x50, 0x82, 0x04, 0xaa, 0xad, 0x50, 0xee, 0xef, 0xad,
	0x85, 0x58, 0x97, 0x78, 0x6c, 0x82, 0xcb, 0x66, 0x75, 0xcc, 0x78, 0x6b, 0x19, 0xc9, 0x1e, 0x4c,
	0x4f, 0xf3, 0xbc, 0x46, 0x29, 0xc9, 0x36, 0xf8, 0x45, 0x1e, 0x7b, 0x87, 0xde, 0xd1, 0x8c, 0xfa,
	0x45, 0x9e, 0xfc, 0x80, 0xf0, 0x9c, 0xdf, 0x62, 0x29, 0x2a, 0x24, 0x09, 0x8c, 0x57, 0xb5, 0xb8,
	0x31, 0xb7, 0xf3, 0xd7, 0xdb, 0xa9, 0xc9, 0x9b, 0xba, 0x97, 0xd4, 0xdc, 0x91, 0x03, 0xf0, 0x95,
	0x88, 0xfd, 0xc3, 0xd1, 0x03, 0x0c, 0x5f, 0x09, 0x92, 0xc2, 0xd4, 0xd9, 0x8b, 0x47, 0x26, 0xcd,
	0x4e, 0x6a, 0x7d, 0xa5, 0x1b, 0x5f, 0xe9, 0x29, 0x6f, 0xe9, 0x86, 0x94, 0x5c, 0x40, 0xf0, 0xae,
	0x14, 0xd9, 0x35, 0xd9, 0x81, 0xa0, 0xe0, 0x39, 0xde, 0x19, 0xf5, 0x31, 0xb5, 0x80, 0x1c, 0xc1,
	0x38, 0x67, 0x8a, 0xc5, 0xfe, 0x23, 0xb9, 0x0c, 0x23, 0x79, 0x09, 0xc1, 0xc7, 0x5a, 0x88, 0x15,
	0x49, 0x20, 0x58, 0xea, 0x8c, 0xae, 0x8c, 0xc8, 0x99, 0x34, 0x2a, 0xd4, 0x5e, 0x69, 0xf2, 0xf9,
	0x2d, 0x72, 0xf5, 0x4f, 0x64, 0x01, 0xf3, 0xcf, 0x35, 0xe3, 0x92, 0x65, 0xaa, 0x10, 0x9c, 0x1c,
	0x00, 0x64, 0x82, 0xab, 0x9a, 0x65, 0xea, 0x72, 0xe1, 0x3a, 0x39, 0x88, 0x90, 0x5d, 0x98, 0x58,
	0xa6, 0x31, 0x3d, 0xa3, 0x0e, 0xe9, 0x52, 0x96, 0x22, 0x6f, 0x1f, 0x6d, 0x8b, 0x61, 0x24, 0x3f,
	0x3d, 0xf8, 0x7f, 0xa0, 0x48, 0x51, 0x36, 0xa5, 0x22, 0x6f, 0x61, 0xae, 0xfa, 0xa0, 0x33, 0x4c,
	0x9c, 0xe1, 0x21, 0x7d, 0x48, 0x23, 0xfb, 0x10, 0xb2, 0x2c, 0xc3, 0x4a, 0x61, 0x6e, 0xfc, 0x84,
	0xb4, 0xc3, 0xe4, 0x29, 0xcc, 0x0a, 0x2e, 0x15, 0xe3, 0x19, 0xca, 0x78, 0x74, 0x38, 0x3a, 0x8a,
	0x68, 0x1f, 0x48, 0x38, 0x84, 0x97, 0x0e, 0x90, 0xff, 0x60, 0x74, 0x8d, 0xad, 0xd1, 0x8c, 0xa8,
	0x3e, 0x92, 0x17, 0x10, 0xdc, 0xb2, 0xb2, 0xc1, 0x47, 0x27, 0x63, 0x29, 0xe4, 0x19, 0x6c, 0x69,
	0x4d, 0x29, 0xcf, 0x74, 0x97, 0x44, 0x69, 0x5a, 0x10, 0xd1, 0xfb, 0xc1, 0x84, 0x43, 0x74, 0xc6,
	0xca, 0xb6, 0x92, 0xe2, 0x4b, 0x5d, 0x28, 0x24, 0xc4, 0x8d, 0xde, 0x8a, 0x9a, 0x33, 0x89, 0xc0,
	0x6b, 0x8c, 0x62, 0x44, 0xbd, 0x46, 0x33, 0x9a, 0x25, 0xab, 0x5d, 0x3a, 0x73, 0xd6, 0x0c, 0x8c,
	0xc7, 0x96, 0x81, 0x1a, 0xad, 0xe2, 0xc0, 0xa2, 0x95, 0x46, 0x59, 0x3c, 0xb1, 0x28, 0x4b, 0x4e,
	0x60, 0xee, 0xf4, 0x28, 0xb2, 0x9c, 0xc4, 0x30, 0xfd, 0xae, 0x75, 0xdd, 0x4c, 0x23, 0xba, 0x81,
	0x7a, 0x65, 0xee, 0x32, 0xa7, 0xea, 0xdf, 0xe9, 0x87, 0xd3, 0xc5, 0xd5, 0xc5, 0x25, 0x2f, 0x14,
	0x79, 0x05, 0x33, 0x66, 0x3f, 0x3f, 0xca, 0xd8, 0x7b, 0x70, 0x29, 0x7a, 0x42, 0xf2, 0x0d, 0xb6,
	0xce, 0x79, 0x56, 0xb7, 0xba, 0xf9, 0x0b, 0x64, 0xa5, 0xfe, 0xf3, 0x8b, 0xf7, 0x57, 0x5d, 0x63,
	0x2d, 0xd0, 0x63, 0xf9, 0x54, 0xac, 0x39, 0x53, 0x4d, 0x8d, 0x4e, 0xb6, 0x0f, 0xe8, 0x37, 0x1f,
	0x04, 0xcf, 0xd0, 0x55, 0x6d, 0x81, 0xfe, 0x74, 0x67, 0x45, 0xf5, 0x15, 0x6b, 0x57, 0xbb, 0x43,
	0xc9, 0xda, 0x78, 0xdd, 0x88, 0xf5, 0x0b, 0xb6, 0x35, 0x5c, 0x30, 0x64, 0x65, 0x37, 0x46, 0x6b,
	0xfe, 0x9e, 0x4d, 0x6a, 0x18, 0xda, 0x96, 0xec, 0x6c, 0x59, 0xf1, 0x3e, 0x90, 0xfc, 0xf2, 0x60,
	0xbe, 0xb8, 0xba, 0xa0, 0x28, 0x2b, 0xc1, 0x25, 0xfe, 0x45, 0xed, 0x04, 0xc2, 0xda, 0x31, 0x9c,
	0xe2, 0x13, 0xa7, 0x38, 0x78, 0x9b, 0x6e, 0x0e, 0xb4, 0x23, 0xef, 0x2b, 0x08, 0xbb, 0xd4, 0xda,
	0x08, 0x4a, 0x59, 0x08, 0xde, 0xcd, 0xaa, 0x0f, 0xf4, 0xc2, 0xfe, 0x50, 0x78, 0x17, 0x26, 0x52,
	0x31, 0xd5, 0x48, 0xe3, 0x3c, 0xa4, 0x0e, 0xdd, 0x2f, 0x6a, 0xfc, 0x67, 0x51, 0xcf, 0x6d, 0xf7,
	0x04, 0x37, 0xa2, 0x55, 0xb3, 0x2c, 0x8b, 0xac, 0x1f, 0x57, 0x1f, 0x58, 0x4e, 0xcc, 0xb7, 0x7f,
	0xf3, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x21, 0x16, 0xea, 0x19, 0x9b, 0x05, 0x00, 0x00,
}
