// Code generated by protoc-gen-go. DO NOT EDIT.
// source: onet.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Address struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcdf24ddc6e333c7, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Envelope struct {
	From                 *Address   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   []*Address `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Message              *any.Any   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Envelope) Reset()         { *m = Envelope{} }
func (m *Envelope) String() string { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()    {}
func (*Envelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcdf24ddc6e333c7, []int{1}
}

func (m *Envelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Envelope.Unmarshal(m, b)
}
func (m *Envelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Envelope.Marshal(b, m, deterministic)
}
func (m *Envelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Envelope.Merge(m, src)
}
func (m *Envelope) XXX_Size() int {
	return xxx_messageInfo_Envelope.Size(m)
}
func (m *Envelope) XXX_DiscardUnknown() {
	xxx_messageInfo_Envelope.DiscardUnknown(m)
}

var xxx_messageInfo_Envelope proto.InternalMessageInfo

func (m *Envelope) GetFrom() *Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Envelope) GetTo() []*Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Envelope) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

type DKGInit struct {
	Addresses            []*Address `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DKGInit) Reset()         { *m = DKGInit{} }
func (m *DKGInit) String() string { return proto.CompactTextString(m) }
func (*DKGInit) ProtoMessage()    {}
func (*DKGInit) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcdf24ddc6e333c7, []int{2}
}

func (m *DKGInit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DKGInit.Unmarshal(m, b)
}
func (m *DKGInit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DKGInit.Marshal(b, m, deterministic)
}
func (m *DKGInit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DKGInit.Merge(m, src)
}
func (m *DKGInit) XXX_Size() int {
	return xxx_messageInfo_DKGInit.Size(m)
}
func (m *DKGInit) XXX_DiscardUnknown() {
	xxx_messageInfo_DKGInit.DiscardUnknown(m)
}

var xxx_messageInfo_DKGInit proto.InternalMessageInfo

func (m *DKGInit) GetAddresses() []*Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type EncryptedDeal struct {
	DHKey                []byte   `protobuf:"bytes,1,opt,name=DHKey,proto3" json:"DHKey,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Nonce                []byte   `protobuf:"bytes,3,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Cipher               []byte   `protobuf:"bytes,4,opt,name=Cipher,proto3" json:"Cipher,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedDeal) Reset()         { *m = EncryptedDeal{} }
func (m *EncryptedDeal) String() string { return proto.CompactTextString(m) }
func (*EncryptedDeal) ProtoMessage()    {}
func (*EncryptedDeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcdf24ddc6e333c7, []int{3}
}

func (m *EncryptedDeal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedDeal.Unmarshal(m, b)
}
func (m *EncryptedDeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedDeal.Marshal(b, m, deterministic)
}
func (m *EncryptedDeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedDeal.Merge(m, src)
}
func (m *EncryptedDeal) XXX_Size() int {
	return xxx_messageInfo_EncryptedDeal.Size(m)
}
func (m *EncryptedDeal) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedDeal.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedDeal proto.InternalMessageInfo

func (m *EncryptedDeal) GetDHKey() []byte {
	if m != nil {
		return m.DHKey
	}
	return nil
}

func (m *EncryptedDeal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *EncryptedDeal) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *EncryptedDeal) GetCipher() []byte {
	if m != nil {
		return m.Cipher
	}
	return nil
}

type DKGDeal struct {
	Index                uint32         `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Deal                 *EncryptedDeal `protobuf:"bytes,2,opt,name=deal,proto3" json:"deal,omitempty"`
	Signature            []byte         `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DKGDeal) Reset()         { *m = DKGDeal{} }
func (m *DKGDeal) String() string { return proto.CompactTextString(m) }
func (*DKGDeal) ProtoMessage()    {}
func (*DKGDeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcdf24ddc6e333c7, []int{4}
}

func (m *DKGDeal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DKGDeal.Unmarshal(m, b)
}
func (m *DKGDeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DKGDeal.Marshal(b, m, deterministic)
}
func (m *DKGDeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DKGDeal.Merge(m, src)
}
func (m *DKGDeal) XXX_Size() int {
	return xxx_messageInfo_DKGDeal.Size(m)
}
func (m *DKGDeal) XXX_DiscardUnknown() {
	xxx_messageInfo_DKGDeal.DiscardUnknown(m)
}

var xxx_messageInfo_DKGDeal proto.InternalMessageInfo

func (m *DKGDeal) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DKGDeal) GetDeal() *EncryptedDeal {
	if m != nil {
		return m.Deal
	}
	return nil
}

func (m *DKGDeal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type DKGResponse struct {
	Index                uint32                `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Response             *DKGResponse_Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DKGResponse) Reset()         { *m = DKGResponse{} }
func (m *DKGResponse) String() string { return proto.CompactTextString(m) }
func (*DKGResponse) ProtoMessage()    {}
func (*DKGResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcdf24ddc6e333c7, []int{5}
}

func (m *DKGResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DKGResponse.Unmarshal(m, b)
}
func (m *DKGResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DKGResponse.Marshal(b, m, deterministic)
}
func (m *DKGResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DKGResponse.Merge(m, src)
}
func (m *DKGResponse) XXX_Size() int {
	return xxx_messageInfo_DKGResponse.Size(m)
}
func (m *DKGResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DKGResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DKGResponse proto.InternalMessageInfo

func (m *DKGResponse) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DKGResponse) GetResponse() *DKGResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type DKGResponse_Response struct {
	SessionID            []byte   `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Status               bool     `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DKGResponse_Response) Reset()         { *m = DKGResponse_Response{} }
func (m *DKGResponse_Response) String() string { return proto.CompactTextString(m) }
func (*DKGResponse_Response) ProtoMessage()    {}
func (*DKGResponse_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcdf24ddc6e333c7, []int{5, 0}
}

func (m *DKGResponse_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DKGResponse_Response.Unmarshal(m, b)
}
func (m *DKGResponse_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DKGResponse_Response.Marshal(b, m, deterministic)
}
func (m *DKGResponse_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DKGResponse_Response.Merge(m, src)
}
func (m *DKGResponse_Response) XXX_Size() int {
	return xxx_messageInfo_DKGResponse_Response.Size(m)
}
func (m *DKGResponse_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_DKGResponse_Response.DiscardUnknown(m)
}

var xxx_messageInfo_DKGResponse_Response proto.InternalMessageInfo

func (m *DKGResponse_Response) GetSessionID() []byte {
	if m != nil {
		return m.SessionID
	}
	return nil
}

func (m *DKGResponse_Response) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DKGResponse_Response) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *DKGResponse_Response) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type DKGDone struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DKGDone) Reset()         { *m = DKGDone{} }
func (m *DKGDone) String() string { return proto.CompactTextString(m) }
func (*DKGDone) ProtoMessage()    {}
func (*DKGDone) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcdf24ddc6e333c7, []int{6}
}

func (m *DKGDone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DKGDone.Unmarshal(m, b)
}
func (m *DKGDone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DKGDone.Marshal(b, m, deterministic)
}
func (m *DKGDone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DKGDone.Merge(m, src)
}
func (m *DKGDone) XXX_Size() int {
	return xxx_messageInfo_DKGDone.Size(m)
}
func (m *DKGDone) XXX_DiscardUnknown() {
	xxx_messageInfo_DKGDone.DiscardUnknown(m)
}

var xxx_messageInfo_DKGDone proto.InternalMessageInfo

func (m *DKGDone) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func init() {
	proto.RegisterType((*Address)(nil), "types.Address")
	proto.RegisterType((*Envelope)(nil), "types.Envelope")
	proto.RegisterType((*DKGInit)(nil), "types.DKGInit")
	proto.RegisterType((*EncryptedDeal)(nil), "types.EncryptedDeal")
	proto.RegisterType((*DKGDeal)(nil), "types.DKGDeal")
	proto.RegisterType((*DKGResponse)(nil), "types.DKGResponse")
	proto.RegisterType((*DKGResponse_Response)(nil), "types.DKGResponse.Response")
	proto.RegisterType((*DKGDone)(nil), "types.DKGDone")
}

func init() { proto.RegisterFile("onet.proto", fileDescriptor_fcdf24ddc6e333c7) }

var fileDescriptor_fcdf24ddc6e333c7 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0xae, 0xda, 0x30,
	0x10, 0x85, 0x95, 0xdc, 0x5c, 0x08, 0xc3, 0xcf, 0xc2, 0x42, 0x28, 0xd0, 0xaa, 0x42, 0xd9, 0x94,
	0x45, 0x65, 0xa4, 0x76, 0xc1, 0x1a, 0x35, 0x88, 0x22, 0xa4, 0x2e, 0xdc, 0x27, 0x08, 0x64, 0x48,
	0x2d, 0x05, 0x3b, 0x8d, 0x9d, 0xaa, 0xd9, 0xf4, 0x21, 0xfb, 0x44, 0x55, 0xec, 0x84, 0x40, 0x45,
	0x77, 0xcc, 0x99, 0x33, 0x73, 0xbe, 0x31, 0x01, 0x90, 0x02, 0x35, 0xcd, 0x0b, 0xa9, 0x25, 0x79,
	0xd5, 0x55, 0x8e, 0x6a, 0x31, 0x4f, 0xa5, 0x4c, 0x33, 0x5c, 0x1b, 0xf1, 0x54, 0x5e, 0xd6, 0xb1,
	0xa8, 0xac, 0x23, 0x9c, 0x43, 0x7f, 0x9b, 0x24, 0x05, 0x2a, 0x45, 0x26, 0xe0, 0xf2, 0x24, 0x70,
	0x96, 0xce, 0x6a, 0xc0, 0x5c, 0x9e, 0x84, 0xbf, 0xc1, 0xdf, 0x89, 0x9f, 0x98, 0xc9, 0x1c, 0x49,
	0x08, 0xde, 0xa5, 0x90, 0x57, 0xd3, 0x1d, 0x7e, 0x9c, 0x50, 0xb3, 0x97, 0x36, 0x93, 0xcc, 0xf4,
	0xc8, 0x3b, 0x70, 0xb5, 0x0c, 0xdc, 0xe5, 0xcb, 0x13, 0x87, 0xab, 0x25, 0xa1, 0xd0, 0xbf, 0xa2,
	0x52, 0x71, 0x8a, 0xc1, 0x8b, 0x59, 0x33, 0xa5, 0x96, 0x8b, 0xb6, 0x5c, 0x74, 0x2b, 0x2a, 0xd6,
	0x9a, 0xc2, 0x0d, 0xf4, 0xa3, 0xe3, 0xfe, 0x20, 0xb8, 0x26, 0x1f, 0x60, 0x10, 0xdb, 0x4d, 0xa8,
	0x02, 0xe7, 0x69, 0x42, 0x67, 0x08, 0x7f, 0xc0, 0x78, 0x27, 0xce, 0x45, 0x95, 0x6b, 0x4c, 0x22,
	0x8c, 0x33, 0x32, 0x85, 0xd7, 0xe8, 0xcb, 0x11, 0x2b, 0x83, 0x3f, 0x62, 0xb6, 0x20, 0x6f, 0x61,
	0xf0, 0x8d, 0xa7, 0x22, 0xd6, 0x65, 0x81, 0x81, 0x6b, 0x3a, 0x9d, 0x50, 0xcf, 0x7c, 0x95, 0xe2,
	0x6c, 0x59, 0x47, 0xcc, 0x16, 0x64, 0x06, 0xbd, 0xcf, 0x3c, 0xff, 0x8e, 0x45, 0xe0, 0x19, 0xb9,
	0xa9, 0xc2, 0xd4, 0xb0, 0xb6, 0x61, 0x5c, 0x24, 0xf8, 0xcb, 0x84, 0x8d, 0x99, 0x2d, 0xc8, 0x0a,
	0xbc, 0x04, 0xe3, 0xcc, 0xe4, 0xd4, 0x97, 0x5b, 0xf8, 0x07, 0x4c, 0x66, 0x1c, 0x35, 0x96, 0xba,
	0x61, 0xd9, 0xf0, 0x4e, 0x08, 0xff, 0x38, 0x30, 0x8c, 0x8e, 0x7b, 0x86, 0x2a, 0x97, 0x42, 0xe1,
	0x7f, 0xd2, 0x36, 0xe0, 0x17, 0x8d, 0xa3, 0x49, 0x7c, 0xd3, 0x24, 0xde, 0xcd, 0xd2, 0xf6, 0x07,
	0xbb, 0x99, 0x17, 0x1a, 0xfc, 0xdb, 0xea, 0x1a, 0x04, 0x95, 0xe2, 0x52, 0x1c, 0xa2, 0xe6, 0xe5,
	0x3a, 0xa1, 0x0b, 0x76, 0xef, 0x83, 0x67, 0xd0, 0x53, 0x3a, 0xd6, 0xa5, 0x32, 0xe4, 0x3e, 0x6b,
	0xaa, 0xc7, 0xa3, 0xbc, 0x7f, 0x8f, 0x7a, 0x6f, 0x5f, 0x4f, 0x0a, 0x13, 0x9a, 0x97, 0xa7, 0x8c,
	0x9f, 0xbb, 0xbf, 0xab, 0x13, 0x4e, 0x3d, 0xf3, 0xa5, 0x7c, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0xa2, 0x73, 0x17, 0x16, 0xe4, 0x02, 0x00, 0x00,
}
