// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package byzcoin

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	skipchain "go.dedis.ch/phoenix/blockchain/skipchain"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Transaction) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type StateMessage struct {
	Proof                *skipchain.ProofMessage `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	Value                []byte                  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *StateMessage) Reset()         { *m = StateMessage{} }
func (m *StateMessage) String() string { return proto.CompactTextString(m) }
func (*StateMessage) ProtoMessage()    {}
func (*StateMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *StateMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateMessage.Unmarshal(m, b)
}
func (m *StateMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateMessage.Marshal(b, m, deterministic)
}
func (m *StateMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateMessage.Merge(m, src)
}
func (m *StateMessage) XXX_Size() int {
	return xxx_messageInfo_StateMessage.Size(m)
}
func (m *StateMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StateMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StateMessage proto.InternalMessageInfo

func (m *StateMessage) GetProof() *skipchain.ProofMessage {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *StateMessage) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "byzcoin.Transaction")
	proto.RegisterType((*StateMessage)(nil), "byzcoin.StateMessage")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xaa, 0xac, 0x4a,
	0xce, 0xcf, 0xcc, 0x93, 0x52, 0x48, 0xca, 0xc9, 0x4f, 0xce, 0x4e, 0xce, 0x48, 0xcc, 0xcc, 0xd3,
	0x2f, 0xce, 0xce, 0x2c, 0x80, 0xb0, 0x4a, 0x2a, 0x0b, 0x60, 0x4a, 0x95, 0x4c, 0xb9, 0xb8, 0x43,
	0x8a, 0x12, 0xf3, 0x8a, 0x13, 0x93, 0x4b, 0x32, 0xf3, 0xf3, 0x84, 0x04, 0xb8, 0x98, 0xb3, 0x53,
	0x2b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4,
	0x9c, 0xd2, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x08, 0x47, 0x29, 0x98, 0x8b, 0x27,
	0xb8, 0x24, 0xb1, 0x24, 0xd5, 0x17, 0x62, 0xb1, 0x90, 0x2e, 0x17, 0x6b, 0x41, 0x51, 0x7e, 0x7e,
	0x1a, 0x58, 0x27, 0xb7, 0x91, 0xb8, 0x1e, 0xdc, 0x36, 0xbd, 0x00, 0x90, 0x38, 0x54, 0x5d, 0x10,
	0x44, 0x15, 0x76, 0x43, 0x93, 0xd8, 0xc0, 0x4e, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x75,
	0x76, 0x41, 0xff, 0xcf, 0x00, 0x00, 0x00,
}
