// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package calypso

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Write struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	U                    []byte   `protobuf:"bytes,2,opt,name=u,proto3" json:"u,omitempty"`
	Ubar                 []byte   `protobuf:"bytes,3,opt,name=ubar,proto3" json:"ubar,omitempty"`
	E                    []byte   `protobuf:"bytes,4,opt,name=e,proto3" json:"e,omitempty"`
	F                    []byte   `protobuf:"bytes,5,opt,name=f,proto3" json:"f,omitempty"`
	C                    []byte   `protobuf:"bytes,6,opt,name=c,proto3" json:"c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Write) Reset()         { *m = Write{} }
func (m *Write) String() string { return proto.CompactTextString(m) }
func (*Write) ProtoMessage()    {}
func (*Write) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Write) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Write.Unmarshal(m, b)
}
func (m *Write) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Write.Marshal(b, m, deterministic)
}
func (m *Write) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Write.Merge(m, src)
}
func (m *Write) XXX_Size() int {
	return xxx_messageInfo_Write.Size(m)
}
func (m *Write) XXX_DiscardUnknown() {
	xxx_messageInfo_Write.DiscardUnknown(m)
}

var xxx_messageInfo_Write proto.InternalMessageInfo

func (m *Write) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Write) GetU() []byte {
	if m != nil {
		return m.U
	}
	return nil
}

func (m *Write) GetUbar() []byte {
	if m != nil {
		return m.Ubar
	}
	return nil
}

func (m *Write) GetE() []byte {
	if m != nil {
		return m.E
	}
	return nil
}

func (m *Write) GetF() []byte {
	if m != nil {
		return m.F
	}
	return nil
}

func (m *Write) GetC() []byte {
	if m != nil {
		return m.C
	}
	return nil
}

type Read struct {
	WriteID              []byte   `protobuf:"bytes,1,opt,name=writeID,proto3" json:"writeID,omitempty"`
	Xc                   []byte   `protobuf:"bytes,2,opt,name=xc,proto3" json:"xc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Read) Reset()         { *m = Read{} }
func (m *Read) String() string { return proto.CompactTextString(m) }
func (*Read) ProtoMessage()    {}
func (*Read) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *Read) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Read.Unmarshal(m, b)
}
func (m *Read) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Read.Marshal(b, m, deterministic)
}
func (m *Read) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Read.Merge(m, src)
}
func (m *Read) XXX_Size() int {
	return xxx_messageInfo_Read.Size(m)
}
func (m *Read) XXX_DiscardUnknown() {
	xxx_messageInfo_Read.DiscardUnknown(m)
}

var xxx_messageInfo_Read proto.InternalMessageInfo

func (m *Read) GetWriteID() []byte {
	if m != nil {
		return m.WriteID
	}
	return nil
}

func (m *Read) GetXc() []byte {
	if m != nil {
		return m.Xc
	}
	return nil
}

func init() {
	proto.RegisterType((*Write)(nil), "calypso.Write")
	proto.RegisterType((*Read)(nil), "calypso.Read")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0x3f, 0x0b, 0xc2, 0x40,
	0x0c, 0x47, 0xb9, 0xda, 0x3f, 0x10, 0x4a, 0x87, 0x4c, 0x19, 0xa5, 0x93, 0x93, 0x08, 0x7e, 0x05,
	0x17, 0xd7, 0x2e, 0xce, 0xe9, 0x35, 0x2d, 0x82, 0xd2, 0xd2, 0xbb, 0xc3, 0xfa, 0xed, 0x25, 0x77,
	0x75, 0xfb, 0xbd, 0xf0, 0xe0, 0x05, 0x9a, 0xb7, 0x38, 0xc7, 0x93, 0xb8, 0xf3, 0xb2, 0xce, 0x7e,
	0xc6, 0xca, 0xf2, 0xeb, 0xbb, 0xb8, 0xb9, 0x9d, 0xa0, 0x78, 0xac, 0x4f, 0x2f, 0x88, 0x90, 0x0f,
	0xec, 0x99, 0xcc, 0xd1, 0x9c, 0xea, 0x2e, 0x6e, 0xac, 0xc1, 0x04, 0xca, 0xe2, 0xc1, 0x04, 0x35,
	0x42, 0xcf, 0x2b, 0x1d, 0x92, 0xa1, 0x5b, 0x0d, 0xa1, 0x3c, 0x19, 0xa2, 0x34, 0x52, 0x91, 0x68,
	0x54, 0xb2, 0x54, 0x26, 0xb2, 0xed, 0x05, 0xf2, 0x4e, 0x78, 0x40, 0x82, 0xea, 0xa3, 0xc1, 0xfb,
	0x6d, 0x4f, 0xfd, 0x11, 0x1b, 0xc8, 0x36, 0xbb, 0xe7, 0xb2, 0xcd, 0xf6, 0x65, 0x7c, 0xf5, 0xfa,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xbb, 0x6b, 0x8a, 0xbc, 0x00, 0x00, 0x00,
}
