// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package globalstate

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Instance struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *any.Any `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	AccessControl        []byte   `protobuf:"bytes,3,opt,name=accessControl,proto3" json:"accessControl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Instance) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Instance) GetAccessControl() []byte {
	if m != nil {
		return m.AccessControl
	}
	return nil
}

func init() {
	proto.RegisterType((*Instance)(nil), "globalstate.Instance")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0xcf, 0xc9, 0x4f,
	0x4a, 0xcc, 0x29, 0x2e, 0x49, 0x2c, 0x49, 0x95, 0x92, 0x4c, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5,
	0x07, 0x4b, 0x25, 0x95, 0xa6, 0xe9, 0x27, 0xe6, 0x55, 0x42, 0xd4, 0x29, 0xe5, 0x71, 0x71, 0x78,
	0xe6, 0x15, 0x97, 0x24, 0xe6, 0x25, 0xa7, 0x0a, 0x09, 0x70, 0x31, 0x67, 0xa7, 0x56, 0x4a, 0x30,
	0x2a, 0x30, 0x6a, 0xf0, 0x04, 0x81, 0x98, 0x42, 0x5a, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9,
	0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x22, 0x7a, 0x10, 0x83, 0xf4, 0x60, 0x06, 0xe9, 0x39,
	0xe6, 0x55, 0x06, 0x41, 0x94, 0x08, 0xa9, 0x70, 0xf1, 0x26, 0x26, 0x27, 0xa7, 0x16, 0x17, 0x3b,
	0xe7, 0xe7, 0x95, 0x14, 0xe5, 0xe7, 0x48, 0x30, 0x83, 0xcd, 0x41, 0x15, 0x4c, 0x62, 0x03, 0x6b,
	0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf1, 0xcb, 0x1b, 0x9a, 0xb0, 0x00, 0x00, 0x00,
}
