// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package skipchain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockMetaData struct {
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockMetaData) Reset()         { *m = BlockMetaData{} }
func (m *BlockMetaData) String() string { return proto.CompactTextString(m) }
func (*BlockMetaData) ProtoMessage()    {}
func (*BlockMetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *BlockMetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMetaData.Unmarshal(m, b)
}
func (m *BlockMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMetaData.Marshal(b, m, deterministic)
}
func (m *BlockMetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMetaData.Merge(m, src)
}
func (m *BlockMetaData) XXX_Size() int {
	return xxx_messageInfo_BlockMetaData.Size(m)
}
func (m *BlockMetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMetaData.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMetaData proto.InternalMessageInfo

func (m *BlockMetaData) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockMetaData)(nil), "skipchain.BlockMetaData")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 95 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2c, 0xce, 0xce, 0x2c,
	0x48, 0xce, 0x48, 0xcc, 0xcc, 0x53, 0xd2, 0xe5, 0xe2, 0x75, 0xca, 0xc9, 0x4f, 0xce, 0xf6, 0x4d,
	0x2d, 0x49, 0x74, 0x49, 0x2c, 0x49, 0x14, 0x92, 0xe1, 0xe2, 0x2c, 0xce, 0x4c, 0xcf, 0x4b, 0x2c,
	0x29, 0x2d, 0x4a, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x09, 0x42, 0x08, 0x24, 0xb1, 0x81, 0x0d,
	0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xc1, 0xaa, 0x8b, 0x52, 0x00, 0x00, 0x00,
}
